services:
  jenkins:
    image: jenkins/jenkins:lts-jdk21
    container_name: jenkins
    restart: always
    volumes:
      - ./jenkins_home:/var/jenkins_home
    networks:
      - backend
    command: >
      bash -c "
        mkdir -p /var/jenkins_home/.ssh &&
        chmod 700 /var/jenkins_home/.ssh &&
        ssh-keyscan -t rsa,ecdsa,ed25519 github.com > /var/jenkins_home/.ssh/known_hosts &&
        chmod 644 /var/jenkins_home/.ssh/known_hosts &&
        chown -R jenkins:jenkins /var/jenkins_home/.ssh &&
        exec /usr/bin/tini -- /usr/local/bin/jenkins.sh
      "

networks:
  backend:
    external: true
